//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regexator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Regexator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and all its content will be deleted permanently..
        /// </summary>
        internal static string _0_AndAllItsContentWillBeDeletedPermanently {
            get {
                return ResourceManager.GetString("_0_AndAllItsContentWillBeDeletedPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be deleted permanently..
        /// </summary>
        internal static string _0_WillBeDeletedPermanently {
            get {
                return ResourceManager.GetString("_0_WillBeDeletedPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+A.
        /// </summary>
        internal static string AltA {
            get {
                return ResourceManager.GetString("AltA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+C.
        /// </summary>
        internal static string AltC {
            get {
                return ResourceManager.GetString("AltC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+R.
        /// </summary>
        internal static string AltR {
            get {
                return ResourceManager.GetString("AltR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+W.
        /// </summary>
        internal static string AltW {
            get {
                return ResourceManager.GetString("AltW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carriage Return + Linefeed.
        /// </summary>
        internal static string CarriageReturnPlusLinefeed {
            get {
                return ResourceManager.GetString("CarriageReturnPlusLinefeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carriage Return Symbol.
        /// </summary>
        internal static string CarriageReturnSymbol {
            get {
                return ResourceManager.GetString("CarriageReturnSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string ColonStr {
            get {
                return ResourceManager.GetString("ColonStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of.
        /// </summary>
        internal static string CopyOf {
            get {
                return ResourceManager.GetString("CopyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        internal static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Pattern.
        /// </summary>
        internal static string CopyPattern {
            get {
                return ResourceManager.GetString("CopyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        internal static string CSharp {
            get {
                return ResourceManager.GetString("CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Verbatim.
        /// </summary>
        internal static string CSharpVerbatim {
            get {
                return ResourceManager.GetString("CSharpVerbatim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+A.
        /// </summary>
        internal static string CtrlA {
            get {
                return ResourceManager.GetString("CtrlA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        internal static string CtrlC {
            get {
                return ResourceManager.GetString("CtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+D.
        /// </summary>
        internal static string CtrlD {
            get {
                return ResourceManager.GetString("CtrlD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Del.
        /// </summary>
        internal static string CtrlDel {
            get {
                return ResourceManager.GetString("CtrlDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Left.
        /// </summary>
        internal static string CtrlLeft {
            get {
                return ResourceManager.GetString("CtrlLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+N.
        /// </summary>
        internal static string CtrlN {
            get {
                return ResourceManager.GetString("CtrlN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+O.
        /// </summary>
        internal static string CtrlO {
            get {
                return ResourceManager.GetString("CtrlO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+P.
        /// </summary>
        internal static string CtrlP {
            get {
                return ResourceManager.GetString("CtrlP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Right.
        /// </summary>
        internal static string CtrlRight {
            get {
                return ResourceManager.GetString("CtrlRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+1.
        /// </summary>
        internal static string CtrlShift1 {
            get {
                return ResourceManager.GetString("CtrlShift1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+2.
        /// </summary>
        internal static string CtrlShift2 {
            get {
                return ResourceManager.GetString("CtrlShift2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+3.
        /// </summary>
        internal static string CtrlShift3 {
            get {
                return ResourceManager.GetString("CtrlShift3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+4.
        /// </summary>
        internal static string CtrlShift4 {
            get {
                return ResourceManager.GetString("CtrlShift4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+5.
        /// </summary>
        internal static string CtrlShift5 {
            get {
                return ResourceManager.GetString("CtrlShift5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+6.
        /// </summary>
        internal static string CtrlShift6 {
            get {
                return ResourceManager.GetString("CtrlShift6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+7.
        /// </summary>
        internal static string CtrlShift7 {
            get {
                return ResourceManager.GetString("CtrlShift7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+8.
        /// </summary>
        internal static string CtrlShift8 {
            get {
                return ResourceManager.GetString("CtrlShift8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+9.
        /// </summary>
        internal static string CtrlShift9 {
            get {
                return ResourceManager.GetString("CtrlShift9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+A.
        /// </summary>
        internal static string CtrlShiftA {
            get {
                return ResourceManager.GetString("CtrlShiftA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+~.
        /// </summary>
        internal static string CtrlShiftTilde {
            get {
                return ResourceManager.GetString("CtrlShiftTilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+V.
        /// </summary>
        internal static string CtrlV {
            get {
                return ResourceManager.GetString("CtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+X.
        /// </summary>
        internal static string CtrlX {
            get {
                return ResourceManager.GetString("CtrlX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Y.
        /// </summary>
        internal static string CtrlY {
            get {
                return ResourceManager.GetString("CtrlY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Z.
        /// </summary>
        internal static string CtrlZ {
            get {
                return ResourceManager.GetString("CtrlZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Line.
        /// </summary>
        internal static string CurrentLine {
            get {
                return ResourceManager.GetString("CurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Line Includes New Line.
        /// </summary>
        internal static string CurrentLineIncludesNewLine {
            get {
                return ResourceManager.GetString("CurrentLineIncludesNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all file inputs.
        /// </summary>
        internal static string DeleteAllFileInputs {
            get {
                return ResourceManager.GetString("DeleteAllFileInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Input Files.
        /// </summary>
        internal static string DeleteAllInputFiles {
            get {
                return ResourceManager.GetString("DeleteAllInputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All input files of the project {0} will deleted permanently..
        /// </summary>
        internal static string DeleteAllInputFilesMsg {
            get {
                return ResourceManager.GetString("DeleteAllInputFilesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Inputs.
        /// </summary>
        internal static string DeleteInputs {
            get {
                return ResourceManager.GetString("DeleteInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopening will cause any changes you made to be discarded. Do you want to reopen {0}?.
        /// </summary>
        internal static string DoYouWantToReopenMsg {
            get {
                return ResourceManager.GetString("DoYouWantToReopenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        internal static string DoYouWantToSaveChangesMsg {
            get {
                return ResourceManager.GetString("DoYouWantToSaveChangesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ….
        /// </summary>
        internal static string EllipsisStr {
            get {
                return ResourceManager.GetString("EllipsisStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Undo/Redo.
        /// </summary>
        internal static string EnableUndoRedo {
            get {
                return ResourceManager.GetString("EnableUndoRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escaped.
        /// </summary>
        internal static string Escaped {
            get {
                return ResourceManager.GetString("Escaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        internal static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing File Input.
        /// </summary>
        internal static string ExistingFileInput {
            get {
                return ResourceManager.GetString("ExistingFileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended.
        /// </summary>
        internal static string Extended {
            get {
                return ResourceManager.GetString("Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2.
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3.
        /// </summary>
        internal static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5.
        /// </summary>
        internal static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7.
        /// </summary>
        internal static string F7 {
            get {
                return ResourceManager.GetString("F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string FileAlreadyExistsDoYouWantToOvervwriteItMsg {
            get {
                return ResourceManager.GetString("FileAlreadyExistsDoYouWantToOvervwriteItMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists..
        /// </summary>
        internal static string FileAlreadyExistsMsg {
            get {
                return ResourceManager.GetString("FileAlreadyExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Input.
        /// </summary>
        internal static string FileInput {
            get {
                return ResourceManager.GetString("FileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is already part of the project..
        /// </summary>
        internal static string FileIsAlreadyPartOfProjectMsg {
            get {
                return ResourceManager.GetString("FileIsAlreadyPartOfProjectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name &apos;{0}&apos; has an invalid format..
        /// </summary>
        internal static string FileNameHasInvalidFormatMsg {
            get {
                return ResourceManager.GetString("FileNameHasInvalidFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Part.
        /// </summary>
        internal static string FileNamePart {
            get {
                return ResourceManager.GetString("FileNamePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; cannot be found.
        ///Do you want to remove this item?.
        /// </summary>
        internal static string FileNotFoundRemoveItemMsg {
            get {
                return ResourceManager.GetString("FileNotFoundRemoveItemMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; cannot be found.
        ///Do you want to remove the reference to it from the recent list?.
        /// </summary>
        internal static string FileNotFoundRemoveItFromRecentMsg {
            get {
                return ResourceManager.GetString("FileNotFoundRemoveItFromRecentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        internal static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System Search.
        /// </summary>
        internal static string FileSystemSearch {
            get {
                return ResourceManager.GetString("FileSystemSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find All.
        /// </summary>
        internal static string FindAll {
            get {
                return ResourceManager.GetString("FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        internal static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find reached the starting point of the search..
        /// </summary>
        internal static string FindReachedStartingPointMsg {
            get {
                return ResourceManager.GetString("FindReachedStartingPointMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Results.
        /// </summary>
        internal static string FindResults {
            get {
                return ResourceManager.GetString("FindResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder name &apos;{0}&apos; has an invalid format..
        /// </summary>
        internal static string FolderNameHasInvalidFormatMsg {
            get {
                return ResourceManager.GetString("FolderNameHasInvalidFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; cannot be found.
        ///Do you want to remove this item?.
        /// </summary>
        internal static string FolderNotFoundRemoveItemMsg {
            get {
                return ResourceManager.GetString("FolderNotFoundRemoveItemMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; cannot be found.
        ///Do you want to remove the reference to it from the recent list?.
        /// </summary>
        internal static string FolderNotFoundRemoveItFromRecentMsg {
            get {
                return ResourceManager.GetString("FolderNotFoundRemoveItFromRecentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following files could not be deleted:.
        /// </summary>
        internal static string FollowingFilesCouldNotBeDeletedMsg {
            get {
                return ResourceManager.GetString("FollowingFilesCouldNotBeDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following files could not be loaded:.
        /// </summary>
        internal static string FollowingFilesCouldNotBeLoadedMsg {
            get {
                return ResourceManager.GetString("FollowingFilesCouldNotBeLoadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following inputs could not be deleted:.
        /// </summary>
        internal static string FollowingInputsCouldNotBeDeletedMsg {
            get {
                return ResourceManager.GetString("FollowingInputsCouldNotBeDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following inputs could not be loaded:.
        /// </summary>
        internal static string FollowingInputsCouldNotBeLoadedMsg {
            get {
                return ResourceManager.GetString("FollowingInputsCouldNotBeLoadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following projects could not be saved:.
        /// </summary>
        internal static string FollowingProjectsCouldNotBeSavedMsg {
            get {
                return ResourceManager.GetString("FollowingProjectsCouldNotBeSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following specified text was not found:.
        /// </summary>
        internal static string FollowingTextWasNotFoundMsg {
            get {
                return ResourceManager.GetString("FollowingTextWasNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Text.
        /// </summary>
        internal static string HighlightText {
            get {
                return ResourceManager.GetString("HighlightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string HyphenStr {
            get {
                return ResourceManager.GetString("HyphenStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoArrowLeft {
            get {
                object obj = ResourceManager.GetObject("IcoArrowLeft", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoArrowRight {
            get {
                object obj = ResourceManager.GetObject("IcoArrowRight", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoArrowRightSmall {
            get {
                object obj = ResourceManager.GetObject("IcoArrowRightSmall", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCheckAll {
            get {
                object obj = ResourceManager.GetObject("IcoCheckAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoClose {
            get {
                object obj = ResourceManager.GetObject("IcoClose", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCode {
            get {
                object obj = ResourceManager.GetObject("IcoCode", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCodeError {
            get {
                object obj = ResourceManager.GetObject("IcoCodeError", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCodeNew {
            get {
                object obj = ResourceManager.GetObject("IcoCodeNew", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCodeOpen {
            get {
                object obj = ResourceManager.GetObject("IcoCodeOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCodeSelected {
            get {
                object obj = ResourceManager.GetObject("IcoCodeSelected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCodeSolution {
            get {
                object obj = ResourceManager.GetObject("IcoCodeSolution", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCollapseAll {
            get {
                object obj = ResourceManager.GetObject("IcoCollapseAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCopy {
            get {
                object obj = ResourceManager.GetObject("IcoCopy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCultureInvariant {
            get {
                object obj = ResourceManager.GetObject("IcoCultureInvariant", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCut {
            get {
                object obj = ResourceManager.GetObject("IcoCut", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoDelete {
            get {
                object obj = ResourceManager.GetObject("IcoDelete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoECMAScript {
            get {
                object obj = ResourceManager.GetObject("IcoECMAScript", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoExpandAll {
            get {
                object obj = ResourceManager.GetObject("IcoExpandAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFile {
            get {
                object obj = ResourceManager.GetObject("IcoFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFileError {
            get {
                object obj = ResourceManager.GetObject("IcoFileError", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFileNew {
            get {
                object obj = ResourceManager.GetObject("IcoFileNew", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFilePlus {
            get {
                object obj = ResourceManager.GetObject("IcoFilePlus", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFileSelected {
            get {
                object obj = ResourceManager.GetObject("IcoFileSelected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFolder {
            get {
                object obj = ResourceManager.GetObject("IcoFolder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFolderOpen {
            get {
                object obj = ResourceManager.GetObject("IcoFolderOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoIgnoreCase {
            get {
                object obj = ResourceManager.GetObject("IcoIgnoreCase", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoInfo {
            get {
                object obj = ResourceManager.GetObject("IcoInfo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoInput {
            get {
                object obj = ResourceManager.GetObject("IcoInput", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoInputNew {
            get {
                object obj = ResourceManager.GetObject("IcoInputNew", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoInputSelected {
            get {
                object obj = ResourceManager.GetObject("IcoInputSelected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoMatchCase {
            get {
                object obj = ResourceManager.GetObject("IcoMatchCase", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoMatchWhole {
            get {
                object obj = ResourceManager.GetObject("IcoMatchWhole", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoNewFolder {
            get {
                object obj = ResourceManager.GetObject("IcoNewFolder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoNewItem {
            get {
                object obj = ResourceManager.GetObject("IcoNewItem", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoNewProjectWithFileInput {
            get {
                object obj = ResourceManager.GetObject("IcoNewProjectWithFileInput", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoNewProjectWithInput {
            get {
                object obj = ResourceManager.GetObject("IcoNewProjectWithInput", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoOpen {
            get {
                object obj = ResourceManager.GetObject("IcoOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoPaste {
            get {
                object obj = ResourceManager.GetObject("IcoPaste", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoReload {
            get {
                object obj = ResourceManager.GetObject("IcoReload", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoRename {
            get {
                object obj = ResourceManager.GetObject("IcoRename", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoReplace {
            get {
                object obj = ResourceManager.GetObject("IcoReplace", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoReplaceAll {
            get {
                object obj = ResourceManager.GetObject("IcoReplaceAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoSnippet {
            get {
                object obj = ResourceManager.GetObject("IcoSnippet", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoSnippetExtensible {
            get {
                object obj = ResourceManager.GetObject("IcoSnippetExtensible", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoSquareBrackets {
            get {
                object obj = ResourceManager.GetObject("IcoSquareBrackets", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoUncheckAll {
            get {
                object obj = ResourceManager.GetObject("IcoUncheckAll", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Groups.
        /// </summary>
        internal static string IgnoredGroups {
            get {
                return ResourceManager.GetString("IgnoredGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is already a part of the project..
        /// </summary>
        internal static string InputIsAlreadyPartOfProject {
            get {
                return ResourceManager.GetString("InputIsAlreadyPartOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is already part of the project. Do you want to overwrite it?.
        /// </summary>
        internal static string InputIsAlreadyPartOfProjectOverwiteMsg {
            get {
                return ResourceManager.GetString("InputIsAlreadyPartOfProjectOverwiteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Sync.
        /// </summary>
        internal static string InputSync {
            get {
                return ResourceManager.GetString("InputSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Extended.
        /// </summary>
        internal static string InsertExtended {
            get {
                return ResourceManager.GetString("InsertExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder(s) and {1} project(s) were removed from recent list..
        /// </summary>
        internal static string InvalidRecentItemsRemovedMsg {
            get {
                return ResourceManager.GetString("InvalidRecentItemsRemovedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value..
        /// </summary>
        internal static string InvalidValueMsg {
            get {
                return ResourceManager.GetString("InvalidValueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and all its content will be deleted permanently..
        /// </summary>
        internal static string Item_AndAllItsContentWillBeDeletedPermanentlyMsg {
            get {
                return ResourceManager.GetString("Item_AndAllItsContentWillBeDeletedPermanentlyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be deleted permanently..
        /// </summary>
        internal static string Item_WillBeDeletedPermanentlyMsg {
            get {
                return ResourceManager.GetString("Item_WillBeDeletedPermanentlyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item &apos;{0}&apos; cannot be found.
        ///Do you want to remove this item?.
        /// </summary>
        internal static string ItemNotFoundRemoveItemMsg {
            get {
                return ResourceManager.GetString("ItemNotFoundRemoveItemMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazy.
        /// </summary>
        internal static string Lazy {
            get {
                return ResourceManager.GetString("Lazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linefeed.
        /// </summary>
        internal static string Linefeed {
            get {
                return ResourceManager.GetString("Linefeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linefeed Symbol.
        /// </summary>
        internal static string LineFeedSymbol {
            get {
                return ResourceManager.GetString("LineFeedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        internal static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word.
        /// </summary>
        internal static string MatchWholeWord {
            get {
                return ResourceManager.GetString("MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; has an invalid format..
        /// </summary>
        internal static string NameHasInvalidFormatMsg {
            get {
                return ResourceManager.GetString("NameHasInvalidFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        internal static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Input.
        /// </summary>
        internal static string NewFileInput {
            get {
                return ResourceManager.GetString("NewFileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Input.
        /// </summary>
        internal static string NewInput {
            get {
                return ResourceManager.GetString("NewInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Line.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New path.
        /// </summary>
        internal static string NewPath {
            get {
                return ResourceManager.GetString("NewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project with File Input.
        /// </summary>
        internal static string NewProjectWithFileInput {
            get {
                return ResourceManager.GetString("NewProjectWithFileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project with Input.
        /// </summary>
        internal static string NewProjectWithInput {
            get {
                return ResourceManager.GetString("NewProjectWithInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Capture Symbol (Table Only).
        /// </summary>
        internal static string NoCaptureSymbolTableOnly {
            get {
                return ResourceManager.GetString("NoCaptureSymbolTableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invalid recent items found..
        /// </summary>
        internal static string NoInvalidRecentItemsFoundMsg {
            get {
                return ResourceManager.GetString("NoInvalidRecentItemsFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Success.
        /// </summary>
        internal static string NoSuccess {
            get {
                return ResourceManager.GetString("NoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No to All.
        /// </summary>
        internal static string NoToAll {
            get {
                return ResourceManager.GetString("NoToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string NumberStr {
            get {
                return ResourceManager.GetString("NumberStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurrence(s) replaced..
        /// </summary>
        internal static string OccurrencesReplacedMsg {
            get {
                return ResourceManager.GetString("OccurrencesReplacedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old path.
        /// </summary>
        internal static string OldPath {
            get {
                return ResourceManager.GetString("OldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer.
        /// </summary>
        internal static string OpenInExplorer {
            get {
                return ResourceManager.GetString("OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Notepad.
        /// </summary>
        internal static string OpenInNotepad {
            get {
                return ResourceManager.GetString("OpenInNotepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Input.
        /// </summary>
        internal static string OpenInput {
            get {
                return ResourceManager.GetString("OpenInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open input cannot be moved..
        /// </summary>
        internal static string OpenInputCannotBeMovedMsg {
            get {
                return ResourceManager.GetString("OpenInputCannotBeMovedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Summary.
        /// </summary>
        internal static string OutputSummary {
            get {
                return ResourceManager.GetString("OutputSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Table.
        /// </summary>
        internal static string OutputTable {
            get {
                return ResourceManager.GetString("OutputTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Text.
        /// </summary>
        internal static string OutputText {
            get {
                return ResourceManager.GetString("OutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        internal static string ParentDirectoryStr {
            get {
                return ResourceManager.GetString("ParentDirectoryStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing error at index.
        /// </summary>
        internal static string ParsingErrorAtIndex {
            get {
                return ResourceManager.GetString("ParsingErrorAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Sync.
        /// </summary>
        internal static string PatternSync {
            get {
                return ResourceManager.GetString("PatternSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string PlusStr {
            get {
                return ResourceManager.GetString("PlusStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Key.
        /// </summary>
        internal static string PressKey {
            get {
                return ResourceManager.GetString("PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project cannot be saved..
        /// </summary>
        internal static string ProjectCannotBeSavedMsg {
            get {
                return ResourceManager.GetString("ProjectCannotBeSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project cannot contain itself as an input..
        /// </summary>
        internal static string ProjectCannotContainItselfAsInputMsg {
            get {
                return ResourceManager.GetString("ProjectCannotContainItselfAsInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} text contains invalid character &apos;{1}&apos;, decimal value {2}, hexadecimal value {3}..
        /// </summary>
        internal static string ProjectContainsInvalidCharMsg {
            get {
                return ResourceManager.GetString("ProjectContainsInvalidCharMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Explorer.
        /// </summary>
        internal static string ProjectExplorer {
            get {
                return ResourceManager.GetString("ProjectExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ProjectFileAlreadyExistsMsg {
            get {
                return ResourceManager.GetString("ProjectFileAlreadyExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project file contains no project element..
        /// </summary>
        internal static string ProjectFileContainsNoProjectElementMsg {
            get {
                return ResourceManager.GetString("ProjectFileContainsNoProjectElementMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project file has been moved..
        /// </summary>
        internal static string ProjectFileMovedMsg {
            get {
                return ResourceManager.GetString("ProjectFileMovedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Info.
        /// </summary>
        internal static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project with File Input.
        /// </summary>
        internal static string ProjectWithFileInput {
            get {
                return ResourceManager.GetString("ProjectWithFileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project with Input.
        /// </summary>
        internal static string ProjectWithInput {
            get {
                return ResourceManager.GetString("ProjectWithInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to the file {0} will be removed from the project..
        /// </summary>
        internal static string ReferenceToFileWillBeRemovedFromProjectMsg {
            get {
                return ResourceManager.GetString("ReferenceToFileWillBeRemovedFromProjectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regexator.
        /// </summary>
        internal static string Regexator {
            get {
                return ResourceManager.GetString("Regexator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RegexatorIcon {
            get {
                object obj = ResourceManager.GetObject("RegexatorIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Options.
        /// </summary>
        internal static string RegexOptions {
            get {
                return ResourceManager.GetString("RegexOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Inputs.
        /// </summary>
        internal static string RemoveAllInputs {
            get {
                return ResourceManager.GetString("RemoveAllInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All inputs and all file inputs references will be permanently deleted from the project {0}..
        /// </summary>
        internal static string RemoveAllInputsMsg {
            get {
                return ResourceManager.GetString("RemoveAllInputsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Project.
        /// </summary>
        internal static string RemoveFromProject {
            get {
                return ResourceManager.GetString("RemoveFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder(s) and {1} project(s) will be permanently removed from recent list..
        /// </summary>
        internal static string RemoveInvalidRecentItemsMsg {
            get {
                return ResourceManager.GetString("RemoveInvalidRecentItemsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        internal static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement.
        /// </summary>
        internal static string Replacement {
            get {
                return ResourceManager.GetString("Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Sync.
        /// </summary>
        internal static string ReplacementSync {
            get {
                return ResourceManager.GetString("ReplacementSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement term.
        /// </summary>
        internal static string ReplacementTerm {
            get {
                return ResourceManager.GetString("ReplacementTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace next.
        /// </summary>
        internal static string ReplaceNext {
            get {
                return ResourceManager.GetString("ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the following items?.
        /// </summary>
        internal static string SaveChangesToFollowingItemsMsg {
            get {
                return ResourceManager.GetString("SaveChangesToFollowingItemsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Input.
        /// </summary>
        internal static string SearchInput {
            get {
                return ResourceManager.GetString("SearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mode.
        /// </summary>
        internal static string SearchMode {
            get {
                return ResourceManager.GetString("SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Option.
        /// </summary>
        internal static string SearchOption {
            get {
                return ResourceManager.GetString("SearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Output.
        /// </summary>
        internal static string SearchOutput {
            get {
                return ResourceManager.GetString("SearchOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Pattern.
        /// </summary>
        internal static string SearchPattern {
            get {
                return ResourceManager.GetString("SearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Replacement.
        /// </summary>
        internal static string SearchReplacement {
            get {
                return ResourceManager.GetString("SearchReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term.
        /// </summary>
        internal static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected items will be deleted permanently..
        /// </summary>
        internal static string SelectedItemsWillBeDeletedPermanentlyMsg {
            get {
                return ResourceManager.GetString("SelectedItemsWillBeDeletedPermanentlyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Set_ {
            get {
                return ResourceManager.GetString("Set_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All.
        /// </summary>
        internal static string SetAll {
            get {
                return ResourceManager.GetString("SetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All Visible.
        /// </summary>
        internal static string SetAllVisible {
            get {
                return ResourceManager.GetString("SetAllVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Visibility.
        /// </summary>
        internal static string SetDefaultVisibility {
            get {
                return ResourceManager.GetString("SetDefaultVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set None.
        /// </summary>
        internal static string SetNone {
            get {
                return ResourceManager.GetString("SetNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Visibility.
        /// </summary>
        internal static string SetVisibility {
            get {
                return ResourceManager.GetString("SetVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Tab.
        /// </summary>
        internal static string ShiftTab {
            get {
                return ResourceManager.GetString("ShiftTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Description.
        /// </summary>
        internal static string ShowDescription {
            get {
                return ResourceManager.GetString("ShowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Files.
        /// </summary>
        internal static string ShowHiddenFiles {
            get {
                return ResourceManager.GetString("ShowHiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hotkey Number.
        /// </summary>
        internal static string ShowHotkeyNumber {
            get {
                return ResourceManager.GetString("ShowHotkeyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        internal static string ShowInfo {
            get {
                return ResourceManager.GetString("ShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Symbol.
        /// </summary>
        internal static string SpaceSymbol {
            get {
                return ResourceManager.GetString("SpaceSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        internal static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Find.
        /// </summary>
        internal static string StopFind {
            get {
                return ResourceManager.GetString("StopFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Symbol.
        /// </summary>
        internal static string TabSymbol {
            get {
                return ResourceManager.GetString("TabSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string Toggle {
            get {
                return ResourceManager.GetString("Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Option.
        /// </summary>
        internal static string ToggleOption {
            get {
                return ResourceManager.GetString("ToggleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Lowercase.
        /// </summary>
        internal static string ToLowercase {
            get {
                return ResourceManager.GetString("ToLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Uppercase.
        /// </summary>
        internal static string ToUppercase {
            get {
                return ResourceManager.GetString("ToUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Current Line Only.
        /// </summary>
        internal static string UseCurrentLineOnly {
            get {
                return ResourceManager.GetString("UseCurrentLineOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Basic.
        /// </summary>
        internal static string VisualBasic {
            get {
                return ResourceManager.GetString("VisualBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB.
        /// </summary>
        internal static string VisualBasicAbbr {
            get {
                return ResourceManager.GetString("VisualBasicAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Text (Table Only).
        /// </summary>
        internal static string WrapTextTableOnly {
            get {
                return ResourceManager.GetString("WrapTextTableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfRegexOptionsItem xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;RegexOptionsItem&gt;
        ///    &lt;Value&gt;Compiled&lt;/Value&gt;
        ///    &lt;Description&gt;Compile the regular expression to an assembly.&lt;/Description&gt;
        ///  &lt;/RegexOptionsItem&gt;
        ///  &lt;RegexOptionsItem&gt;
        ///    &lt;Value&gt;CultureInvariant&lt;/Value&gt;
        ///    &lt;Description&gt;Ignore cultural differences between languages.&lt;/Description&gt;
        ///  &lt;/RegexOptionsItem&gt;
        ///  &lt;RegexOptionsItem&gt;
        ///    &lt;Value [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlRegexOptionsItems {
            get {
                return ResourceManager.GetString("XmlRegexOptionsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes to All.
        /// </summary>
        internal static string YesToAll {
            get {
                return ResourceManager.GetString("YesToAll", resourceCulture);
            }
        }
    }
}
